engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
    checks:
      guard-for-in:
        enabled: false
      complexity:
        enabled: false
      wrap-iife:
        enabled: false
      no-new-func:
        enabled: false
      global-require:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- docs/
