engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      guard-for-in:
        enabled: false
      complexity:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- docs/
