
<div id="code"></div>
<div id="result"></div>


<script id="source">
    new CodeView({
        selector: '#result',
        content: 'var content = "initial content";',
    })
    .write('a = \'55\'')
    .write([
        'var a = true;',
        '// some comment',
        'a = 100;'
    ])
    .write('a = 123;');
</script>

<!-- Write #source content to #code div -->
<script src="write-source.js"></script>