
<div id="code"></div>
<div id="result"></div>

<script id="source">

    // this obviously will fail so add content manualy

    new CodeView('#code')
        .write('new CodeView({')
        .write('    selector: \'#result\',')
        .write('    url: \'url/to/local/file\'')
        .write('});');

    new CodeView('#result')
        .write('var text = \'Hi, from your file. Original. huh ?\';');

</script>