<div class="jumbotron container setup-wrapper">

    <div>Just include this</div>
    <input type="text" class="form-control width-400" value='<script src="code-view.js"></script>' />
    <br />

    <div>or this, if you want to use it like jquery plugin</div>
    <input type="text" class="form-control width-400" value='<script src="jquery.code-view.js"></script>' />
    <br />

    <div>or their minified versions from <i>src/</i> folder in this repo.</div>
    <br />

    <div>Then choose one of the color schemes in <i>themes/</i> folder. For example</div>
    <input type="text" class="form-control width-400" value='<link rel="stylesheet" href="sublime-monokai.css">' />
    <br />

    <div><strong class="fs-20">That`s it !<strong></div>

    <script>
        $('.setup-wrapper .form-control.width-400').each(function () {
            $(this).width(parseInt($(this).val().length * 6.5));
        });
    </script>
</div>