<div class="error-404 centered">
    <div class="error-code">404</div>
    <div class="error-title">OH NO !</div>
    <div class="error-subtitle">YOU BROKE THE INTERNET.</div>
    <div class="error-description">
    <br>
    <br>
    <br>
    Well.. technically speaking, you just went to a page that only exists in your mind.
    <br>
    <br>
    Don`t worry. We all make mistakes.
    </div>
</div>